### ISSUE TITLE
new reddit layout

### ISSUE THREAD

**Issue by shuckle16** [tossj/no-mobile-reddit#1]
Hey tossj,

Thanks for developing this handy addon! I've noticed lately, however, that it is not functioning for me as expected. I think it's due to the changes in reddit's UI. Not sure how to do this exactly, but I think that by redirecting any reddit URL to old.reddit.com will get it to work as it used to...

Thanks again!

**Comment by tossj** [comment]
Hi @shuckle16,

The extension continues to work for me, so I have some questions.

1. Could you confirm that you're seeing the mobile site, and not seeing the newly designed desktop site? That is, the website tries to get you to install the app, and then you have to click continue to mobile site.
    - If you are seeing the newly designed desktop site, is it hard to use in the same way the mobile site is?
2. What device are you using, and what is your viewport? You can check your viewport [here](http://whatismyviewport.com/).
3. What version of Firefox are you using? You can go to [about:firefox](about:firefox) and the version number is in the top-left corner.
4. How do you visit reddit when this error occurs? Do you open the browser and type in the address, or do you click a link in another app (like email or RSS) and then open the link in the browser, or something else?

**Comment by shuckle16** [comment]
1. reddit must be doing some A/B test; when I am on a regular tab it shows "new reddit", but when I switch to a private tab I see that the app works still. The new reddit is pretty hard for me to use on my device.
2. I'm using a samsung galaxy s7, and the viewport is 360px x 560px
3. I'm on firefox for android 60.0.1
4. I've got a couple of subreddits bookmarked, but I sometimes just type the address of another subreddit (like reddit.com/r/economics)

**Comment by tossj** [comment]
OK, I'll look into adding a redirect functionality from `reddit.com` to `old.reddit.com`.

**Comment by tossj** [comment]
I've uploaded the new version to AMO. Firefox should automatically update the add-on for you. The option to redirect is in the add-on's settings page.

**Comment by mirh** [comment]
Could it be enabled by default?

**Comment by tossj** [comment]
@mirh I've enabled it by default in the new version 1.2.0, which should update automatically. If you already downloaded the extension, you'll have to enable it yourself by going to `about:addons`, and check the checkbox on the extension's options page. You can also uninstall and reinstall the extension, and it'll be enabled by default.

Thanks for the feedback. In the future, please open a new issue to give your feedback.
